const dummyData = {
  users: [
    {
      id: "user001",
      clerkId: "ev1",
      name: "Alice EV",
      email: "alice.ev@example.com",
      phone_number: 1234567890,
      host_id: null,
      car_model: "Tesla Model X",
    },
    {
      id: "user002",
      clerkId: "ev2",
      name: "Bob EV",
      email: "bob.ev@example.com",
      phone_number: 9876543210,
      host_id: "user003",
      car_model: "Hyundai IONIQ 5",
    },
    {
      id: "user003",
      clerkId: "ev3",
      name: "Charlie Host",
      email: "charlie.host@example.com",
      phone_number: 1112223333,
      charger_listings: ["charger001", "charger002"],
      car_model: null,
    },
  ],
  charger_listings: [
    {
      id: "charger001",
      host_id: "user003",
      charger_type: "Level 2",
      power_output_kw: 7.2,
      connector_type: "J1772",
      address: "297 Main St, Manhattan",
      latitude: 40.7331, // Manhattan, NYC
      longitude: -74, // Manhattan, NYC
      availability_schedule: "Mon-Fri: 9am-5pm",
      price_per_hour: 5.0,
      min_price: 2.5,
      images:
        "https://qmerit.com/wp-content/uploads/2024/05/Qmerit-home-ev-charging-station-cost.jpg",
      is_active: true,
      instructions: "Park in spot #3 and plug in.",
      created_at: "2025-05-01T08:00:00Z",
      updated_at: "2025-05-20T10:00:00Z",
    },
    {
      id: "charger002",
      host_id: "user003",
      charger_type: "DC Fast",
      power_output_kw: 50.0,
      connector_type: "CCS",
      address: "456 Market Ave, Manhattan",
      latitude: 40.7431,
      longitude: -73.9712,
      availability_schedule: "24/7",
      price_per_hour: 12.0,
      min_price: 5.0,
      images:
        "https://www.brickunderground.com/sites/default/files/2023-09/iStock-1344638615.jpg",
      is_active: false,
      instructions: "Use app to unlock charger.",
      created_at: "2025-05-05T09:00:00Z",
      updated_at: "2025-05-20T10:30:00Z",
    },
  ],
  bookings: [
    {
      id: "booking001",
      charger_listings_id: "charger001",
      charger_listings_address: "142 Main St, Manhattan",
      host_id: "user003",
      ev_owner_id: "user001",
      start_time: "2025-05-21T14:00:00Z",
      end_time: "2025-05-21T16:00:00Z",
      total_cost: 10.0,
      status: "online",
      payment_status: "paid",
      rating_by_driver: 5,
      rating_by_host: 4,
      battery_level: "72%",
      images:
        "https://www.brickunderground.com/sites/default/files/2023-09/iStock-1344638615.jpg",
    },
  ],
  payment_invoice: [
    {
      id: "invoice001",
      booking_id: "booking001",
      amount: 10.0,
      currency: "USD",
      payment_method: "credit_card",
      transaction_id: "txn_123456789",
      status: "completed",
      created_at: "2025-05-21T13:50:00Z",
      recipient: {
        id: "user003",
        email: "charlie.host@example.com",
      },
      payer: {
        id: "user001",
        email: "alice.ev@example.com",
      },
    },
  ],
  notifications: [
    {
      id: "notif001",
      user_id: "user001",
      title: "Booking Confirmed",
      message: "Your booking at 123 Main St has been confirmed.",
      type: "booking",
      is_read: true,
      created_at: "2025-05-21T13:55:00Z",
    },
    {
      id: "notif002",
      user_id: "user003",
      title: "New Booking Received",
      message: "You have a new booking from alice.ev@example.com.",
      type: "booking",
      is_read: false,
      created_at: "2025-05-21T13:56:00Z",
    },
  ],
};

export default dummyData;