/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth/login` | `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth/signup` | `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/ev_owner` | `/home/ev_owner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listing/ev_owner` | `/listing/ev_owner`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/auth/login` | `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/auth/signup` | `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home/ev_owner` | `/home/ev_owner`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/listing/ev_owner` | `/listing/ev_owner`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/auth/signup${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home/ev_owner${`?${string}` | `#${string}` | ''}` | `/home/ev_owner${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/listing/ev_owner${`?${string}` | `#${string}` | ''}` | `/listing/ev_owner${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth/login` | `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth/signup` | `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home/ev_owner` | `/home/ev_owner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/listing/ev_owner` | `/listing/ev_owner`; params?: Router.UnknownInputParams; };
    }
  }
}
